name: alchemyrohan

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -U wheel

      - name: Build and test
        run: |
          python setup.py sdist bdist_wheel
          python -m pip install dist/*.whl
